apiVersion: v1
kind: Service
metadata:
  name: es-master
spec:
  selector:
    application: es-master
  ports:
  - name: transport
    port: 9300
    targetPort: 9300
  - name: http
    port: 9200
    targetPort: 9200
