apiVersion: v1
kind: Service
metadata:
  name: es6-master
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    application: es6
    role: master
  ports:
  - name: transport
    port: 9300
    targetPort: 9300
  - name: http
    port: 9200
    targetPort: 9200
