apiVersion: v1
kind: ConfigMap
metadata:
  name: es6-config
data:
  elasticsearch.yml: |
    cluster.name: es6-operator-e2e
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: es6-master
    discovery.zen.minimum_master_nodes: 1
