apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es7-master
spec:
  replicas: 1
  serviceName: es7-master
  selector:
    matchLabels:
      application: es7
      role: master
  template:
    metadata:
      labels:
        application: es7
        role: master
    spec:
      serviceAccountName: operator
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox:1.30
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 50m
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        resources:
          requests:
            memory: 600Mi
            cpu: 100m
          limits:
            memory: 600Mi
            cpu: 100m
        securityContext:
          runAsUser: 1000
        image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.1"
        env:
        - name: "node.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "ES_JAVA_OPTS"
          value: "-Xmx400m -Xms400m"
        - name: node.master
          value: "true"
        - name: node.data
          value: "false"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 20
        ports:
        - containerPort: 9200
          name: es-http
        - containerPort: 9300
          name: es-transport
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: es-data
          emptyDir: {}
        - name: es-config
          configMap:
            name: es7-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
