apiVersion: v1
kind: ConfigMap
metadata:
  name: es8-config
data:
  elasticsearch.yml: |
    cluster.name: es8-operator-e2e
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.seed_hosts: [es8-master]
    cluster.initial_master_nodes: [es8-master-0]
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
