run:
linters-settings:
  revive:
    rules:
      # Adjust rules related to code simplicity, readability, and maintainability
      - name: exported
        severity: warning
      - name: cyclomatic
        severity: warning
        arguments: [20]  # Set the maximum allowed cyclomatic complexity to 20


linters:
  disable-all: true
  enable:
    - staticcheck
    - ineffassign
    - revive
    - goimports
    - errcheck
issues:
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
