apiVersion: zalando.org/v1
kind: ElasticsearchDataSet
metadata:
  labels:
    application: elasticsearch
    role: data
    group: simple
  name: es-data-simple
  namespace: es-operator-demo
spec:
  excludeSystemIndices: true
  scaling:
    enabled: true
    diskUsagePercentScaledownWatermark: 80
    minReplicas: 3
    maxReplicas: 100
    minIndexReplicas: 1
    maxIndexReplicas: 50
    minShardsPerNode: 2
    maxShardsPerNode: 50
    scaleDownCPUBoundary: 30
    scaleUpCPUBoundary: 90
    scaleDownThresholdDurationSeconds: 6
    scaleUpThresholdDurationSeconds: 30
    scaleDownCooldownSeconds: 18
    scaleUpCooldownSeconds: 12
  template:
    metadata:
      labels:
        application: elasticsearch
        role: data
        group: simple
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: elasticsearch
        env:
        - name: "node.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "node.attr.group"
          value: "simple"
        - name: "node.master"
          value: "false"
        - name: "node.data"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xmx500m -Xms500m"
        image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
        ports:
        - containerPort: 9300
          name: transport
        readinessProbe:
          httpGet:
            path: /_cat/master
            port: 9200
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
          requests:
            cpu: 500m
            memory: 800Mi
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: data
        emptyDir: {}
      - name: elasticsearch-config
        configMap:
          name: es-config
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
