apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticsearchmetricsets.zalando.org
spec:
  group: zalando.org
  version: v1
  scope: Namespaced
  names:
    kind: ElasticsearchMetricSet
    singular: elasticsearchmetricset
    plural: elasticsearchmetricsets
    shortNames:
    - ems
    categories:
    - all
